services:
  app:
    image: liounex/test-dev:latest
    ports:
      - "8000:8000"
    networks:
      - app-network

  nginx:
    container_name: nginx-app
    restart: always
    build: 
      context: ./jobs
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

networks:
  app-network:

